### ISSUE TITLE
`help` returns no config found error

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#10]
If you run `help` out of the context of a directory that has a config file, we end up with an `[ERROR] A hubspot.config.yml file could not be found` error in the help output

<img width="650" alt="Screen Shot 2019-10-25 at 11 39 21 AM" src="https://user-images.githubusercontent.com/35824747/67584654-1da4df00-f71c-11e9-837b-50a0013c3a0a.png">

**Comment by corymartin** [comment]
Usage tracking tries pulling in the config.  It early returns if not present, but we need to silence the config error logging.

**Comment by gcorne** [comment]
I believe that @miketalley fixed this.
