### ISSUE TITLE
Improve "config file already exists" error messaging 

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#110]
<img width="658" alt="Screen Shot 2020-02-25 at 8 34 07 PM" src="https://user-images.githubusercontent.com/35824747/75303402-9e7d0000-580e-11ea-8f76-a4d7fbd21566.png">

This error message does not help users figure out what they can do to move forward. It should instruct users to run the auth command to update an existing config. 

cc @wmurray

**Comment by iamw11y** [comment]
I think we can follow a similar format to @HubSpot/LocalDevAuth#31 where we provide both an error message and an info message, like so:

> Error: The config file "/Users/wspiro/Desktop/local-cms-development/hubspot.config.yml" already exists.
> Info: To update an existing config file, use the "hs auth" command.

**Comment by iamw11y** [comment]
I think we can follow a similar format to @HubSpotProtected/LocalDevAuth#31 where we provide both an error message and an info message, like so:

> Error: The config file "/Users/wspiro/Desktop/local-cms-development/hubspot.config.yml" already exists.
> Info: To update an existing config file, use the "hs auth" command.

**Comment by miketalley** [comment]
We currently don't have a `logger.info` method to log like this. It would live in the [logger](https://github.com/HubSpot/hubspot-cms-tools/blob/d98866808d337a6c56f02fec6622a2e00ab06822/packages/cms-lib/logger.js#L30). Should be a quick fix to add this -- do we have any thoughts around the color that "[Info]" should be?

/cc @iamw11y
