### ISSUE TITLE
Fix vulnerabilities with ESLint dependencies minimist and acorn

### ISSUE THREAD

**Issue by miketalley** [HubSpot/hubspot-cms-tools#133]
We have a couple [vulnerabilities that started showing in Github](https://github.com/HubSpot/hubspot-cms-tools/network/alerts). It looks like they are related to ESLint dependencies.

Once ESLint updates their dependencies, we should be able to upgrade the version that we are using to fix the issue.

See https://github.com/eslint/eslint/issues/13050

**Comment by miketalley** [comment]
Looks like ESLint is not going to update their deps because there is a [workaround for this here](https://github.com/eslint/eslint/issues/13050#issuecomment-600311496).

I'm going to recreate `yarn.lock` and see if that solves this.

**Comment by gcorne** [comment]
After updating lerna and its deps in #158, this is fixed.
