### ISSUE TITLE
Make `hs init` errors more helpful

### ISSUE THREAD

**Issue by miketalley** [HubSpot/hubspot-cms-tools#142]
![image](https://user-images.githubusercontent.com/6472448/77665939-b2736900-6f56-11ea-9b15-40bc2118008f.png)

**Comment by miketalley** [comment]
Closing this as `hs init` on windows with the path for `hubspot.config.yml` being `/Users/<username>` was causing issues - we switched the path back to the cwd

https://github.com/HubSpot/hubspot-cms-tools/pull/145

**Comment by gcorne** [comment]
Even with those changes, we still need to improve this messaging.

**Comment by gcorne** [comment]
Addressed via #163
