### ISSUE TITLE
Add supported types to hs help create

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#146]
We should add the supported `<type>`s to the CLI documentation when you run `hs help create`.

**Comment by miketalley** [comment]
I'm going to work on adding this so it will show a list of all supported `options` for each command when running `hs help` and also when running an incomplete command like `hs auth`.

**Comment by miketalley** [comment]
Fixed `hs auth` help in https://github.com/HubSpot/hubspot-cms-tools/pull/155/files
Fixed `hs create` help in https://github.com/HubSpot/hubspot-cms-tools/pull/159
