### ISSUE TITLE
Add supported types to hs help auth

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#147]
We should add the supported `<type>`s to the CLI documentation when you run `hs help auth`.

**Comment by bgoodies** [comment]
@miketalley were you looking at this already?

**Comment by miketalley** [comment]
I had a recent PR that made help messages display when running incomplete commands -- like `hs auth` -- but the help text currently does not indicate the full list of options. I will work on this.

**Comment by miketalley** [comment]
I'm going to close this in preference of #146 and work on displaying supported `options` for all commands in their help text.
