### ISSUE TITLE
Return site preview URL(s) on deploy

### ISSUE THREAD

**Issue by axellabs** [HubSpot/hubspot-cms-tools#16]
Not sure if this is possible, but could we return the preview url of the pages changed on `hs upload` and the first upload instance of `hs watch`? 

I think this would be useful because while it would require initial portal setup, it would make it easier for new devs to jump onto projects and emulate a common local development flow.

**Comment by gcorne** [comment]
@axellabs I am curious about how you see this working, especially when there are a lot of templates and pages using those templates. Do you think that you could share an example for what you would like the output to be when running the commands?
