### ISSUE TITLE
Support HubDB fetch to cwd

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#186]
If you omit `dest`, we should fetch to the cwd like other commands do

**Comment by williamspiro** [comment]
My misunderstanding was that <dest> actually needs to be the name of the file to be created locally

**Comment by anthmatic** [comment]
@williamspiro we could make `dest` optional and the filename could default to the table name, id, or combo of both.

`12345_ice_cream_flavors.json`

Would that work?

**Comment by williamspiro** [comment]
Yea, from my perspective we should make the HubDB commands work similar to fetching Design Manager files, which is why I ran into this confusion. As you note, where `dest` is an optional directory for the HubDB file to be fetched. 

I think `name`.json would make sense, especially once https://github.com/HubSpot/hubspot-cms-tools/issues/185 is implemented. 

Prior to enforcing a separate `name` and `label` for HubDB tables, there are many tables with `name`s that break some standard conventions, and even tables with duplicate `name`s in single account which is something to keep in mind.

**Comment by anthmatic** [comment]
Sounds good.

>Prior to enforcing a separate name and label for HubDB tables, there are many tables with names that break some standard conventions, and even tables with duplicate names in single account which is something to keep in mind.

good call, thanks

**Comment by gcorne** [comment]
This was done via #205
