### ISSUE TITLE
List folder difference

### ISSUE THREAD

**Issue by Igcorreia** [HubSpot/hubspot-cms-tools#208]
When we work with Watch activated the system syncs all files as soon as they exist. If I rename one file, hub post will have both the old and new files. It would be great to have a list of all files that exist in the cloud folder vs our local folder.

**Comment by gcorne** [comment]
@Igcorreia one option that you can use when running watch is `hs watch --remove` which will delete files from HubSpot when they are removed locally. This helps when files are renamed, but is a bit dangerous so we don't enable it by default anymore.

**Comment by Igcorreia** [comment]
Thanks worked. This is good for early new setups.
