### ISSUE TITLE
[Question] Should watch be updated to not upload all watched files/folder initially

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#213]
There has been quite a few users who would prefer if the initial upload of watched files/folders only happened if they so specified that should happen. As in, rather than setting `--disable-initial` to disable the initial upload, the initial upload does not occur by default, and a user would need to run `watch` with `--enable-initial` (or something similar) for the initial upload to happen.

User sometimes forget to use the `--disable-initial` flag when starting a `watch`, which can cause a large number of files to quickly become incorrect without an easy way to roll back. 

This would be a pretty major departure from the existing behavior. 

Some conversation on the topic https://hubspotdev.slack.com/archives/CLJJXGTC0/p1590284153389900

cc @gcorne @miketalley @iamw11y 

Thoughts? 

**UPDATE: We are going to move forward with work to make the initial auto-upload opt-in**
Changes which need to be made at the same time:

- [ ]  `hs watch` does not auto-upload the watched dir by default (@gcorne) 
- [ ]  A new `--enable-initial` flag added to watch, to make the initial auto-upload happen (@gcorne) 
- [ ]  Some sort of log when running `hs watch` that mentions the change, for any existing users who are confused why an initial auto-upload is not happening. (@gcorne) 
- [ ]  CLI reference docs on `watch` updated with new behavior and flag. We should maybe also have a callout on this command for a while that explains this change, in case anyone looks at the docs, and they reflect different behavior than their version. (@TheWebTech)
- [ ]  The quick start guide updated to include the `--enable-initial` flag for uploading the project (we also need to do some digging to make sure no other docs need to be updated. For example, https://github.com/HubSpot/cms-theme-boilerplate#to-download-the-hubspot-cms-boilerplate-using-the-hubspot-cms-cli (@TheWebTech).
- [ ]  We could include this change in a changelog post, as well as a slack post (@TheWebTech)

**Comment by iamw11y** [comment]
Are users making this request because they would prefer that the behavior is disabled by default or because there's no way to revert when they forget to set that flag? If it's the former and they're in the minority, then it's probably not worth changing given the majority of users prefer that the initial upload is enabled by default. (Side question: is one or the other more common in general? Is there a common practice we could follow?) If it's the latter, then is there a better way we could address this, taking into account whether most users would prefer this functionality enabled or disabled by default (meaning, if they prefer disabled then we make the change)? Otherwise, should we provide a way to roll back the upload, if feasible?

**Comment by dennisedson** [comment]
I cannot speak for everyone, but I would prefer it being disabled. As with cutting wood, you can always cut more, but you can't uncut something.
I do not have you gauge the majority on this one

**Comment by danaholdt** [comment]
I am with the Edson on this. Initially disabled as it can cause major conflict when working in the same portal with multiple developers. We can't always be working in the most pristine of workflows.

**Comment by melindagreen** [comment]
i almost never want the initial upload to happen. i fetch whenever i start work, so an initial upload is redundant.

**Comment by kieranja** [comment]
I don't use hs watch for this very reason. I personally feel default behaviour shouldn't be so destructive. I feel the name "watch" is a bit too innocent for the potential deep sinking feeling this command creates while it "watches" your development environment burn.

**Comment by williamspiro** [comment]
I think we could also start with properly documenting `watch`. I am not sure the initial upload of watched files/folders is clear unless you read down to the `--disable-initial` option. We could also include an example of running the command with the `--disable-initial` option.
cc @TheWebTech

**Comment by dennisedson** [comment]
@williamspiro , better documentation would be a good start, but i am still pushing for changing default behavior.  you can always push content with `upload` , but you can't unpush it if you forgot the `--disable-initial`

**Comment by gcorne** [comment]
I am not opposed to making this change, but I do think that multiple developers using the same customer account together with `hs watch` is risky. I'd love to better understand why working that way is preferred over using separate sandboxes for each developer perhaps together with GitHub or some other source control solution. The collaboration experience is much smoother and less risky.

**Comment by dennisedson** [comment]
@gcorne, i understand what you are saying, but we have attempted to work on individual sandboxes for another site build and while it lowered the risk, it was tedious.  Each of us had to build out the page on our sandbox and add whatever modules to that page.  This was all done while using github and we used an action to push to production once it hit master.  Maybe we should consider setting up some demo videos from various people/teams in  the community and hubspot to display their workflows.  I am actively thinking about that now, actually...stay tuned

**Comment by iamw11y** [comment]
> you can always push content with `upload`, but you can't unpush it if you forgot the `--disable-initial`

This is as good an argument as any for making the change. If we change the default and the user forgets to enable the initial upload, nothing will happen and they can run the appropriate command. But if we change nothing, then by the time the user realizes they forgot to disable the initial upload, they'll be stuck manually sorting out their environment.

> We could also include an example of running the command with the --disable-initial option.

This could be a smart way to surface the functionality more immediately to increase awareness in the interim, giving us time to determine if/when we make the change to disable the initial upload by default.

**Comment by gcorne** [comment]
I am good with making this change. @iamw11y do you think we should consider adding any special messaging? I wonder if some copy that described both `--initial-upload` (name TBD) and `--remove` might help with the transition as well as awareness around both options.
