### ISSUE TITLE
Support hs filemanager fetch

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#214]
For https://github.com/HubSpot/hubspot-cms-tools/issues/13

Adding support for `hs filemanager fetch` to expand upon the `filemanager` subcommand.

**Comment by williamspiro** [comment]
FTP is being sunset this week (May 27), so adding support for `hs filemanager fetch` will be valuable in aiding in the transition for some existing FTP users. 

cc @gcorne @miketalley @bgoodies @KatzMitch @anthmatic

**Comment by stefenphelps** [comment]
Use case: download all images so you can then resize/optimize them locally and then re-upload.
