### ISSUE TITLE
Can't upload changes to templates?

### ISSUE THREAD

**Issue by morrislaptop** [HubSpot/hubspot-cms-tools#216]
When I run `hs upload "hubspot/Coded files" "Coded files" --portal DR-Stage` I get lots of errors saying that `Another template with id xxxxx already exists with the path Custom/email/xxxxx.html`

How do I publish changes back into Hubspot?

**Comment by gcorne** [comment]
@morrislaptop not sure why you are hitting issues here. @mattcoley @liamrharwood do either of you happen to know of why this might be occurring? I think it could be due to the file being read-only.

**Comment by morrislaptop** [comment]
Any update?

**Comment by anthmatic** [comment]
@morrislaptop I'm unable to reproduce this issue. Are you able to share a little more context? Specifically the file names that aren't uploading?

**Comment by morrislaptop** [comment]
Seems to work now
