### ISSUE TITLE
Add `hs create vue-app` 

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cms-tools#217]
When demoing `hs create react-app`, there was a lot of interest in [Vue.js](https://vuejs.org/), so it makes sense to create a similar demo app that helps users set up a CMS project using Vue.

**Comment by edodusi** [comment]
@gcorne we have created a module boilerplate for Vue.js (2.x), it's heavily inspired by the cms-react-boilerplate, uses TypeScript and builds with webpack, using the webpack-cms-plugins for watcher and upload.

You can find it here https://github.com/sparkfabrik/hubspot-cms-vuejs-boilerplate

We are open to any of your requests or suggestions, if you think this is good enough to become an officially supported boilerplate for an `hs create vue-app` command we would be happy to share our work with you and actively support the project.

**Comment by miketalley** [comment]
Thanks for sharing this @edodusi, it's really great to see open source HubSpot projects like this out there!

Your comment is quite timely, as I was planning to start looking into this today. I'll take a look at your repo and keep you posted!

**Comment by edodusi** [comment]
Thanks @miketalley! Looking forward to it!

**Comment by miketalley** [comment]
@edodusi After discussion with the team we decided to build a Vue boilerplate without docker and typescript. Thanks for sharing your repo with us though, it looks great!

**Comment by edodusi** [comment]
thanks @miketalley, I think we'll stay on our boilerplate because the benefits of using typescript for development are too big to ignore, but we'll keep an eye on your js version and I hope we'll continue to share our progresses!
