### ISSUE TITLE
Path issue?

### ISSUE THREAD

**Issue by danielchimen** [HubSpot/hubspot-cms-tools#229]
Hello!

I have the following in my package.json file;

`"deploy": "npx hs upload \"2020 Theme\" \"2020 Theme\"",`

It works perfectly on my Mac OS machine seen below;

`daniel@Daniels-Mini: ~/www/acs (master) $ hs upload "2020 Theme" "2020 Theme"
[SUCCESS] Uploading files from "2020 Theme" to "2020 Theme" in the Design Manager...`

However when trying to run the command on my windows machine I get the following error:

`[ERROR] The path "2020 Theme" is not a path to a file or folder`

Anyone have an idea as to why this might be happening? 

Any help would be much appreciated! Thanks

**Comment by danielchimen** [comment]
Solved this by simply removing the whitespace from the folder name! 😆

**Comment by anthmatic** [comment]
@danielchimen glad you got this sorted for now. This is a bug with `npx` on Windows. We've got an open issue to track this: https://github.com/HubSpot/hubspot-cms-tools/issues/85
