### ISSUE TITLE
Add label option with hs create

### ISSUE THREAD

**Issue by matiasvad** [HubSpot/hubspot-cms-tools#243]
Idea: Being able to set the label of the module, template and so on, directly when creating the given type, e.g. `hs create module form --label="Form" <dest>`

The reasoning this idea is to keep the local code easy-to-navigate and keep in line with formatting like lowercase, no special chars, no spaces etc, for folders, but still be able to show the pretty version (label) to the end user.

An alternative solution, is to have the `"label": ""` displayed in the `meta.json` upon creation, so people unfamiliar with the `label` option, will know that they can use it.

**Comment by anthmatic** [comment]
The `create` command is not really set up to take extra arguments right now, but I do think it would be useful to include a default `label` in `meta.json`

**Comment by gcorne** [comment]
> The create command is not really set up to take extra arguments right now, but I do think it would be useful to include a default label in meta.json

I agree that adding a label is good step. We also introduce using prompts when creating `hs create function`. It may make sense to do that for more of the scaffolds that we provide.
