### ISSUE TITLE
Investigate 502 Bad Gateway HTML overwriting image files when fetching

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#265]
Reported https://hubspotdev.slack.com/archives/CLJJXGTC0/p1595969690247400 and https://hubspotdev.slack.com/archives/CLJJXGTC0/p1592250962497600

It sounds like when you fetch assets, if they return a 502 Bad Gateway, the file gets replaced by the HTML response
```
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```

**Comment by anthmatic** [comment]
It looks like we either need to clean up the writable stream if the request is no good or wait until after the file is fetched to write the file. @miketalley do you have any opinions/ideas here?

**Comment by williamspiro** [comment]
cc @HubSpot/cms-developer-experience I think we should figure this one out to make sure folks running into it do not lose trust in the CLI
