### ISSUE TITLE
Incorporate ignore rules via `.hsignore` and the default rules when initializing watcher

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cms-tools#28]

**Comment by gcorne** [comment]
The `chokidar` library, which we use for file watching, uses [https://github.com/micromatch/anymatch](anymatch) for ignore patterns, so we'll need to somehow convert our git-style ignore rules to anymatch.

**Comment by kieranja** [comment]
@gcorne have submitted a PR - https://github.com/HubSpot/hubspot-cms-tools/pull/33

**Comment by gcorne** [comment]
Fixed via #33.
