### ISSUE TITLE
Add option to the watch command to disable initial upload

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cms-tools#29]

**Comment by gcorne** [comment]
@corymartin @williamspiro @miketalley any thoughts on the name of the option? Two ideas are `hs watch --initial false` and `hs watch --disable-initial`. I am leaning towards the second.

**Comment by miketalley** [comment]
> @corymartin @williamspiro @miketalley any thoughts on the name of the option? Two ideas are `hs watch --initial false` and `hs watch --disable-initial`. I am leaning towards the second.

I like `hs watch --disable-initial` also

**Comment by corymartin** [comment]
I'd rather the option be even more self documenting, even if the initial thing should be self evident to the purpose of `watch`.

```bash
hs watch --disable-initial-upload
```

At some point we should organize short options, like `hs watch -d` in this case.
