### ISSUE TITLE
Error when going through create module flow

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#296]
When going through the `hs create module` flow, I am getting this error
<img width="1081" alt="Screen Shot 2020-08-21 at 12 33 36 PM" src="https://user-images.githubusercontent.com/35824747/90913766-b9d65b80-e3aa-11ea-9b6e-da3c595530fc.png">

This is happening in version `@hubspot/cms-cli@1.1.10`

**Comment by gcorne** [comment]
@drewjenkins mind fixing this up?
