### ISSUE TITLE
Add hs ls command to get asset listing

### ISSUE THREAD

**Issue by TheWebTech** [HubSpot/hubspot-cms-tools#309]
To enable developers to work more and more locally without relying on the design manager as much, it would be nice to have an `ls` like command.

hypothetical command:

`hs ls <path> --portal=<portalId>`

`path` is optional, if left blank returns root directory.

When executed returns a list of files and folders in the specified directory.

Use cases:

- Developers can identify the folder names/paths that they want to fetch/upload to easier without relying on the Design Manager UI.

- Could also be used as a safe "testing" mechanism to ensure a hubspot.config.yml file is properly configured. (see [Slack](https://hubspotdev.slack.com/archives/CLJJXGTC0/p1599232631088400?thread_ts=1598973935.077900&cid=CLJJXGTC0))

caveat there is no concept of `hs cd` and that may be requested after. A `cd` command could be confusing to work with.

**Comment by miketalley** [comment]
I think the best way to go about this would be to add a GET for `/folders/by-path/{fullPath}` that returns the `folder` and then if we have a match we can GET `/folders/contents` using that `folder.id` and list the `folders` and `files` from the response.
