### ISSUE TITLE
typo in hs create module

### ISSUE THREAD

**Issue by TheWebTech** [HubSpot/hubspot-cms-tools#311]
Minor typo when running hs create module.

Prompts for if global - "y/N" inconsistent capitalization.

Suggestion use lowercase

**Comment by anthmatic** [comment]
This is intentional, the capital 'N' means that is the default option. It's generated by the inquirer library that we use for the prompts, but if anyone has a suggestion for a better way to word that promt feel free to throw it out there!

**Comment by TheWebTech** [comment]
Interesting. Haven't noticed that design pattern before in other stuff. That said its easily overlooked, because it doesnt negatively affect anything.

Its completely fine then. Will close this.
