### ISSUE TITLE
Unable to upload assets to HubSpot

### ISSUE THREAD

**Issue by winduptoy** [HubSpot/hubspot-cms-tools#322]
I'm using v2.0.1 of the CLI tools.

When running the command `hs upload mytheme mytheme` I get the following errors:

```
[ERROR] Uploading file "/home/me/mytheme/fields.json" to "mytheme/fields.json" failed
[ERROR] Unable to upload "/home/me/mytheme/fields.json". The post failed because "mytheme/fields.json" was not found in portal XXXXXXX. Unable to find model with id 34719888101
[ERROR] Uploading file "/home/me/mytheme/images/template-previews/membership-reset-password-request.png" to "mytheme/images/template-previews/membership-reset-password-request.png" failed
[ERROR] Unable to upload "/home/me/mytheme/images/template-previews/membership-reset-password-request.png". The post failed because "mytheme/images/template-previews/membership-reset-password-request.png" was not found in portal XXXXXXX. Unable to find model with id 34719892051

... snip ...

[SUCCESS] Uploading files to "mytheme" in the Design Manager is complete
```

If I go to the Design Manager and delete the `mytheme` folder and try again, the issue still persists. Uploading to a new non-existent folder like `mytheme2` will temporarily fix it, but I eventually hit these errors again.

So I guess the issues here are:
1. I can't upload assets, so how do I get around this?
2. A better error message may be in order, as I don't understand what these missing models are or where to begin handling this myself.

**Comment by gcorne** [comment]
@winduptoy Thanks for the report. We're looking into it.

**Comment by mattcoley** [comment]
We found a subtle bug that was preventing a deleted asset from being restored. The bug is now fixed so you should be able to upload again.
