### ISSUE TITLE
Watch --remove with different src and dest folders

### ISSUE THREAD

**Issue by Schascha** [HubSpot/hubspot-cms-tools#326]
The remove flag can only delete files if src and dest are identical:

`hs watch --remove example example` 

If I use a different src, like:

`hs watch --remove dist example` 

e.g. as part in a build process, it will produce console log `The "example" is not a path to a directory` and deleted files are ignored.

Is there a solution to use a different src location? 

Thanks

**Comment by gcorne** [comment]
Thanks for the report. This looks to be a bug. We'll get it fixed up.

**Comment by gcorne** [comment]
@Schascha I dug into this a bit and wasn't able to reproduce using the example that you provided. We do consider the destination when constructing the file path that should be removed from the Design Manager. Could you provide a bit more context around how your build process is set up?

**Comment by Schascha** [comment]
Thanks for your help. Had to change the project setup for other reasons and work now in the same directory.
