### ISSUE TITLE
Warning messages for unsupported file types

### ISSUE THREAD

**Issue by axellabs** [HubSpot/hubspot-cms-tools#35]
When uploading and syncing files to the design manager, SVG's are silently ignored, causing references in the code to silently fail. There should be a warning when this file type fails to upload. 

https://git.hubteam.com/HubSpot/CMS-Developer-Infrastructure/issues/210

```html
<div class="hero">
  <div class="container flex">
      <div class="hero__text">
          <h1>Solutions for Your Business Made Exceptionally Easy</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam laoreet sapien sed efficitur.</p>
          <a class="button--primary" href="https://hubspot.com">Get Started </a>
      </div>
      <div class="hero__visual">
          <img src={{ get_asset_url("../../images/screen1.svg") }} alt="Example screen" />
          <img src={{ get_asset_url("../../images/screen1.png") }} alt="Example screen" />
      </div>
  </div>
</div>
```
### results in:

<img width="1194" alt="Screen Shot 2019-12-17 at 11 22 29 AM" src="https://user-images.githubusercontent.com/48642024/71112059-b7c35980-2198-11ea-890a-5687693759cf.png">

![511f3c80-20c1-11ea-8704-984131177edd](https://user-images.githubusercontent.com/48642024/71112130-e0e3ea00-2198-11ea-8d61-5cfd4c97659e.png)

**Comment by williamspiro** [comment]
@axellabs what version of the CLI are you on? .svg support was recently added.

**Comment by axellabs** [comment]
Let me update and report back.

**Comment by axellabs** [comment]
Okay, so sorry for this, debugging this issue has been a lot. Everything is working.
