### ISSUE TITLE
hs lint error message unhelpful

### ISSUE THREAD

**Issue by TheWebTech** [HubSpot/hubspot-cms-tools#380]
## Description and Context
Tried using `hs lint` on module. Get error:

```
[ERROR] A StatusCodeError has occurred. 403 - {"status":"error","message":"This oauth-token (#######################) does not have proper permissions! (requires any of [content-editor-access, content-access])","correlationId":"#################"}
```
This looks like a scope issue. Ran the auth command again deactivated personal access key reactivated with all available permissions on that screen. Error still occurs.

CLI Version used: 2.2.0

### Steps to reproduce
use `hs lint` on a module

## Expected behavior
warnings and errors printed to terminal for the current file, template, theme, or module.

## Who to Notify
@drewjenkins - sorry if this wasn't one of your projects, just seemd like this feature came in one of the more recent changes.

**Comment by gcorne** [comment]
Hmm…I don't think `hs lint` should be documented or show up in help. It was something that was sort of an experiment that doesn't work so well as it works currently.
