### ISSUE TITLE
Add support for using environment variables instead of a config file

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cms-tools#4]
In order to leverage the CLI, there are situations where environment variables are preferred to limit the exposure of secrets. For example, instead of having to generate a config file in a Github action, it would be nice if a developer could just use environment variables.

**Comment by mattcoley** [comment]
Using environmental variables and having a configure step to set up these variables for users would be preferable. See [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html) for an example.
