### ISSUE TITLE
@hubspot/create-cms-project success message 

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#44]
Tell the user they successfully scaffolded the boilerplate project.

@markhazlewood any suggestions on copy here?

**Comment by williamspiro** [comment]
@iamw11y @gcorne @miketalley we should get this one before the next round of grading. Maybe we can align the messaging with https://github.com/HubSpot/hubspot-cms-tools/issues/43

**Comment by iamw11y** [comment]
We should maintain consistency with the format of success messages that were created in #52, but I have a few questions:

1. Can we be specific about what type of project has been created? I've seen chatter about website boilerplate vs. blog vs. landing page (see: #54), so it might be worth specifying which it was.
2. Do we need to clarify where the project was created by passing in the directory?

If the answer to both is yes, then I would go with the following message:

`Success: your new boilerplate website project has been created in /my-directory.`

If we have to be really generic, I would go with something like this:

`Success: your new project has been created.`

**Comment by gcorne** [comment]
@miketalley is going to tackle this.

**Comment by williamspiro** [comment]
Awesome! @miketalley let me know when this gets out so I can update the placeholder [here](https://designers.hubspot.com/guides/getting-started#quick_start).
