### ISSUE TITLE
Improve server error console messaging 

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#45]
```
[ERROR] Uploading file "/Users/wspiro/Desktop/local-cms-dev/...." failed
[ERROR] Unable to upload "/Users/wspiro/Desktop/local-cms-dev/...". The post to "dev-website..." on portal 6906341 failed due to a server error. internal error
```

We should make this error contain more useful information for users, noting to try again and reach out to support if the issue persists. 

I also think "... on portal" should be _in portal_? 

@iamw11y

**Comment by miketalley** [comment]
@williamspiro @iamw11y what are your thoughts on the method of directing them to support. Should we just say "please try again or reach out to support if the issue persists" or also provide a link to a help page or contact info?

**Comment by iamw11y** [comment]
How about "Please try again or visit https://help.hubspot.com/ to submit a ticket or contact HubSpot Support if the issue persists." for additional guidance?

**Comment by iamw11y** [comment]
**Note:** One thing to verify would be what level of support and what avenues are available to developers. We'll need to make sure that we don't send them to the above site if they won't qualify or there's no means of addressing their issues through that ticket system.

**Comment by iamw11y** [comment]
Recognizing this issue is now closed, another possibility crossed my mind which could sidestep the question of whether the user qualifies for support calls or tickets: what if we sent them to the Developer Slack? The invite URL is https://designers.hubspot.com/slack but there may be a more direct link that only send users there if they aren't logged in.

**Comment by miketalley** [comment]
I was thinking this would be a good resource as well. Would it be possible
to link the developer slack on help.hubspot.com somewhere? We could then
have one link to a robust list of resources.
