### ISSUE TITLE
Remove git requirement for @hubspot/create-cms-project

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#54]
We should remove the need to have `git` installed to run `@hubspot/create-cms-project`, the created project should not be connected to the https://github.com/HubSpot/cms-theme-boilerplate repo

**Comment by williamspiro** [comment]
@gcorne @miketalley @corymartin how heavy of a lift would this be? This would help reduce the number of hoops folks need to jump through to get started (install git). Additionally, the link between their created project and the boilerplate itself is a little confusing.

**Comment by gcorne** [comment]
My thought is that we could leverage GitHub releases and the associated .zip file to scaffold instead of git clone. I also think we should build this into `hs create` instead of the `@hubspot/create-cms-project` so that the user would do `hs create website-theme my-theme`.

**Comment by gcorne** [comment]
I think we can use https://www.npmjs.com/package/extract-zip to extract the zip.

**Comment by corymartin** [comment]
Both Slate and React create app determine if the resource is Git hosted or local.

E.g. Slate's implementation.
https://github.com/Shopify/slate/blob/d3b4cd867f91d0c8b56c61f438c096090dee1c59/packages/create-slate-theme/create-slate-theme.js#L155-L163

We could check if the local resource is a dir, zip archive, or git url and do whatever is appropriate.

**Comment by corymartin** [comment]
@gcorne Is `"website-theme"` the `<type>` we want to go with?  Any reason not to shorten it to `"theme"`?

**Comment by corymartin** [comment]
```shell
# Download and unzip from GH 
# https://github.com/HubSpot/hubspot-cms-tools/archive/master.zip
hs create theme https://github.com/HubSpot/hubspot-cms-tools my-theme

# Clone from GH
hs create --ssh theme git@github.com:HubSpot/hubspot-cms-tools.git my-theme
hs create theme https://github.com/HubSpot/hubspot-cms-tools.git my-theme

# Create from local dir or zip?
hs create theme ./local/dir my-theme
```

**Comment by gcorne** [comment]
> @gcorne Is "website-theme" the <type> we want to go with? Any reason not to shorten it to "theme"?

I think we're going to have separate boilerplates for blog and landing-page themes.

**Comment by gcorne** [comment]
@corymartin when it comes to the boilerplates that we're going to maintain, I think it is worth keeping the commands as simple as possible. We know the source of the code so we should be able to keep the URL in some constant in the codebase. If we are concerned about the URL breaking, we could see about a simple BE API.

**Comment by corymartin** [comment]
Ok. I was still following in the tracks that Facebook and Shopify set in their "create" commands.
So we just want to copy our latest boilerplate?

**Comment by corymartin** [comment]
I also noted that the zip URI's will reflect tags and branches.

E.g.
```
# Branches
https://github.com/HubSpot/cms-theme-boilerplate/archive/master.zip
https://github.com/HubSpot/cms-theme-boilerplate/archive/another-branch.zip
# Tag
https://github.com/HubSpot/cms-theme-boilerplate/archive/v1.0.5.zip
```

We should consider tagging boilerplate releases and a `--theme-version=2` option in the tool.

**Comment by gcorne** [comment]
@corymartin I think https://help.github.com/en/github/administering-a-repository/linking-to-releases#linking-to-the-latest-release should work
