### ISSUE TITLE
Add Support For "Notify" Argument When Using "Watch" Command

### ISSUE THREAD

**Issue by clnmcgrw** [HubSpot/hubspot-cms-tools#59]
When using the cms-cli's `watch` command for local dev workflows, it can sometimes be useful to know when the changed files have finished uploading (to trigger a browser refresh for example).

Shopify has a similar cli tool for their platform, which does this by allowing you to pass a notify argument (`--notify=path/to/local-file.whatev`) - then a change event is triggered to that local file after every upload. [https://shopify.github.io/themekit/commands/#watch](https://shopify.github.io/themekit/commands/#watch)

From there, devs can watch the local file and do whatever they need.  It's very handy for workflows that proxy a live site w/ a dev server like browsersync (example - https://medium.com/@markbrouch/edit-live-sites-on-the-fly-with-browsersync-426690dac3f1).

Curious if others see that as beneficial and a feature worth adding?  Thanks

**Comment by gcorne** [comment]
Yeah, I agree it is a solid idea. The intent behind #2 was to add this, so I am going to close this out . as a duplicate.
