### ISSUE TITLE
Duplicate filemanager folders being created

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#63]
When uploaded a certain project of files to the filemanager, the root folder and its child files seem to be getting uploaded multiple times (sometimes twice, sometimes four times). For example, I just uploaded "A_Folder" once, but I see it four times in the [File Manager](https://app.hubspotqa.com/files/100754221/). Additionally, only one of the root folders contains the "Photos" sub-folder. I am going to share the project of files internally. 

I can reproduce this on version 1.0.6

@paulca55 reported this issue. 

cc @gcorne @corymartin @miketalley

**Comment by gcorne** [comment]
There is a race condition on the backend that folks are working out. In the meantime, I am going to adjust the command to upload files in series to workaround the issue.
