### ISSUE TITLE
filemanager subcommand skipping file uploads on second upload

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-tools#64]
This might be related to https://github.com/HubSpot/hubspot-cms-tools/issues/63 and is also reported by @paulca55.

When he runs a `filemanager upload` for the second time on a project, none of the files get uploaded (and we console log no files getting uploaded). If he renames the project he is uploading, the files will then get uploaded. However, again, upon trying to upload for a second time, the same issue occurs. This is happening with the project of files I shared fro https://github.com/HubSpot/hubspot-cms-tools/issues/63. I am going to share a video of this behavior internally. 

I am unable to reproduce this issue. 

cc @gcorne @corymartin @miketalley

**Comment by gcorne** [comment]
@paulca55 are you still experiencing this issue?
